### ISSUE TITLE
Automated binary releases

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/unclog#17]
We need to automatically release binaries for the following Rust build targets:

- `x86_64-unknown-linux-musl`
- `x86_64-apple-darwin`
- `x86_64-pc-windows-gnu`

I tried a simple approach with [this GitHub action](https://github.com/informalsystems/unclog/blob/1f76e5eec93bca39ec7067e368eb46921808097c/.github/workflows/release.yml), but it unfortunately doesn't work because we need to preinstall the OpenSSL development libraries before building (using [git2-rs](https://github.com/rust-lang/git2-rs), which I currently use for inferring configuration of a project, requires this).

**Comment by thanethomson** [comment]
#18 didn't actually work, so re-opening.

**Comment by rnbguy** [comment]
I noticed `ibc-rs` is using [`taiki-e/upload-rust-binary-action`](https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases). I would love to create a PR if that is ok with you.

**Comment by rnbguy** [comment]
Along with that, there exits [cargo-binstall](https://github.com/ryankurte/cargo-binstall#supporting-binary-installation) which allows `cargo binstall` without actually compiling. It would be nice to have just this on CI.

```sh
cargo install cargo-binstall
cargo binstall unclog
```

There also exists a similar project - [alsuren/cargo-quickinstall](https://github.com/alsuren/cargo-quickinstall).

**Comment by rnbguy** [comment]
Looks like `quickinstall` is [setup with external servers with build caches](https://github.com/alsuren/cargo-quickinstall#original-problem-statement).
I just ran a CI with `cargo quickinstall unclog` and it took only 2 seconds :)
![image](https://user-images.githubusercontent.com/3789449/142912688-3fa9b399-1ba1-4cb5-b584-68ded32992b6.png)
